http:
  routers:
    auth:
      rule: "PathPrefix(`/auth`)"
      service: auth-service
      entryPoints: [web]
      priority: 10
      middlewares:
        - strip-auth-prefix

    api:
      rule: "PathPrefix(`/`)"
      service: api-service
      entryPoints: [web]
      priority: 1

  middlewares:
    strip-auth-prefix:
      stripPrefix:
        prefixes:
          - "/auth"
          
  services:
    auth-service:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:3001"

    api-service:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:8000"